# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute coefficients and sigma in a weighted linear regression
#'
#' In order to speed up the function of lm in R, I write this Rcpp file to solve
#' coefficients and sigma on my own. Firstly, it needs RcppArmadillo to make basic
#' linear computation. We should first input design matrix X, response vector y,
#' weights diagnoal matrix W, the size of whole data and the rank p.
#' Then coef = (X^T W X)^(-1)(X^T W y) and sigma = sqrt(W * (X*coef - y)^2/(n-p)).
#'
#'
#' @param X design matrix with rank p.
#' @param y response vector
#' @param W weighted diagonal matrix
#' @param n the size of whole data
#' @param p the rank of X
#' @return a list including coef and sigma
#' @export
lmC <- function(X, y, W, n, p) {
    .Call(`_blblm_lmC`, X, y, W, n, p)
}

